<?xml version="1.0" encoding="UTF-8"?>
<testExecutions version="1">
  <file path="/home/daniele/Scrivania/PULSeBS-Team8/client/src/Components/Teacher/CancelForm.test.js">
    <testCase name="Cancel lecture button works" duration="246"/>
  </file>
  <file path="/home/daniele/Scrivania/PULSeBS-Team8/client/src/pages/logins/index.test.js">
    <testCase name="Input handle login with non-empty email and password" duration="622"/>
    <testCase name="Input handle login with empty email and password" duration="182"/>
  </file>
  <file path="/home/daniele/Scrivania/PULSeBS-Team8/client/src/Components/Student/RegisteredCourses.test.js">
    <testCase name="RegisteredCourses page rendering with lectures list" duration="462"/>
    <testCase name="RegisteredCourses page rendering without lectures list" duration="279"/>
    <testCase name="Successfully cancel a reservation" duration="640"/>
  </file>
  <file path="/home/daniele/Scrivania/PULSeBS-Team8/client/src/Components/Student/AvailableCourses.test.js">
    <testCase name="AvailableCourses page rendering with lectures list" duration="87"/>
    <testCase name="AvailableCourses page rendering without lectures list" duration="13"/>
    <testCase name="Successfully book a lecture" duration="105"/>
    <testCase name="Should fail to book a lecture" duration="180"/>
  </file>
  <file path="/home/daniele/Scrivania/PULSeBS-Team8/client/src/index.test.js">
    <testCase name="Application root should render without crashing" duration="20"/>
  </file>
  <file path="/home/daniele/Scrivania/PULSeBS-Team8/client/src/App.test.js">
    <testCase name="full app rendering/navigating" duration="528"/>
    <testCase name="random routes redirect to home page" duration="27"/>
  </file>
  <file path="/home/daniele/Scrivania/PULSeBS-Team8/client/src/Components/Teacher/StudentList.test.js">
    <testCase name="StudentList modal rendering with student list" duration="182"/>
    <testCase name="StudentList modal rendering without student list" duration="45"/>
  </file>
  <file path="/home/daniele/Scrivania/PULSeBS-Team8/client/src/Components/Student/StudentPage.test.js">
    <testCase name="Student page rendering/navigation" duration="41"/>
  </file>
  <file path="/home/daniele/Scrivania/PULSeBS-Team8/client/src/Components/Teacher/TeacherPage.test.js">
    <testCase name="Teacher page rendering with lectures" duration="1139">
      <failure message="Error: expect(jest.fn()).toHaveBeenCalledTimes(expected)"><![CDATA[Error: expect(jest.fn()).toHaveBeenCalledTimes(expected)

Expected number of calls: 1
Received number of calls: 0

<html>
  <head />
  <body>
    <div>
      <div
        class="container-fluid"
        data-testid="teacher-page"
      >
        <div
          class="fade alert alert-danger show"
          data-testid="error-message"
          role="alert"
        >
          Server Error
        </div>
      </div>
    </div>
  </body>
</html>
    at /home/daniele/Scrivania/PULSeBS-Team8/client/src/Components/Teacher/TeacherPage.test.js:31:47
    at runWithExpensiveErrorDiagnosticsDisabled (/home/daniele/Scrivania/PULSeBS-Team8/client/node_modules/@testing-library/dom/dist/config.js:51:12)
    at checkCallback (/home/daniele/Scrivania/PULSeBS-Team8/client/node_modules/@testing-library/dom/dist/wait-for.js:103:77)
    at Timeout.task [as _onTimeout] (/home/daniele/Scrivania/PULSeBS-Team8/client/node_modules/jsdom/lib/jsdom/browser/Window.js:391:19)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)]]></failure>
    </testCase>
    <testCase name="Teacher page rendering with failing lectures api" duration="1019">
      <failure message="Error: thrown: Object {"><![CDATA[Error: thrown: Object {
  "status": 401,
}
    at _getError (/home/daniele/Scrivania/PULSeBS-Team8/client/node_modules/jest-circus/build/utils.js:442:18)
    at Array.map (<anonymous>)
    at makeSingleTestResult (/home/daniele/Scrivania/PULSeBS-Team8/client/node_modules/jest-circus/build/utils.js:383:38)
    at makeTestResults (/home/daniele/Scrivania/PULSeBS-Team8/client/node_modules/jest-circus/build/utils.js:408:26)
    at makeRunResult (/home/daniele/Scrivania/PULSeBS-Team8/client/node_modules/jest-circus/build/utils.js:333:16)
    at run (/home/daniele/Scrivania/PULSeBS-Team8/client/node_modules/jest-circus/build/run.js:29:35)
    at runAndTransformResultsToJestFormat (/home/daniele/Scrivania/PULSeBS-Team8/client/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:176:21)
    at jestAdapter (/home/daniele/Scrivania/PULSeBS-Team8/client/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:109:19)
    at runTestInternal (/home/daniele/Scrivania/PULSeBS-Team8/client/node_modules/jest-runner/build/runTest.js:380:16)
    at runTest (/home/daniele/Scrivania/PULSeBS-Team8/client/node_modules/jest-runner/build/runTest.js:472:34)
    at Object.worker (/home/daniele/Scrivania/PULSeBS-Team8/client/node_modules/jest-runner/build/testWorker.js:133:12)]]></failure>
      <failure message="Error: expect(jest.fn()).toHaveBeenCalledTimes(expected)"><![CDATA[Error: expect(jest.fn()).toHaveBeenCalledTimes(expected)

Expected number of calls: 1
Received number of calls: 0

<html>
  <head />
  <body>
    <div>
      <div
        class="container-fluid"
        data-testid="teacher-page"
      >
        <div
          class="fade alert alert-danger show"
          data-testid="error-message"
          role="alert"
        >
          Server Error
        </div>
      </div>
    </div>
  </body>
</html>
    at /home/daniele/Scrivania/PULSeBS-Team8/client/src/Components/Teacher/TeacherPage.test.js:48:47
    at runWithExpensiveErrorDiagnosticsDisabled (/home/daniele/Scrivania/PULSeBS-Team8/client/node_modules/@testing-library/dom/dist/config.js:51:12)
    at checkCallback (/home/daniele/Scrivania/PULSeBS-Team8/client/node_modules/@testing-library/dom/dist/wait-for.js:103:77)
    at Timeout.task [as _onTimeout] (/home/daniele/Scrivania/PULSeBS-Team8/client/node_modules/jsdom/lib/jsdom/browser/Window.js:391:19)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)]]></failure>
    </testCase>
    <testCase name="LectureTable filter lectures button works" duration="1012">
      <failure message="Error: expect(jest.fn()).toHaveBeenCalledTimes(expected)"><![CDATA[Error: expect(jest.fn()).toHaveBeenCalledTimes(expected)

Expected number of calls: 1
Received number of calls: 0

<html>
  <head />
  <body>
    <div>
      <div
        class="container-fluid"
        data-testid="teacher-page"
      >
        <div
          class="fade alert alert-danger show"
          data-testid="error-message"
          role="alert"
        >
          Server Error
        </div>
      </div>
    </div>
  </body>
</html>
    at /home/daniele/Scrivania/PULSeBS-Team8/client/src/Components/Teacher/TeacherPage.test.js:63:47
    at runWithExpensiveErrorDiagnosticsDisabled (/home/daniele/Scrivania/PULSeBS-Team8/client/node_modules/@testing-library/dom/dist/config.js:51:12)
    at checkCallback (/home/daniele/Scrivania/PULSeBS-Team8/client/node_modules/@testing-library/dom/dist/wait-for.js:103:77)
    at Timeout.task [as _onTimeout] (/home/daniele/Scrivania/PULSeBS-Team8/client/node_modules/jsdom/lib/jsdom/browser/Window.js:391:19)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)]]></failure>
    </testCase>
  </file>
</testExecutions>